artifact_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1Gxjzm3dQXFt1zPPnirFQw5JEOinv4AQU/view?usp=sharing
  local_data_file: artifacts/data_ingestion/water_potability.csv
data_validation:
  root_dir: artifacts/data_validation
  data_file: artifacts/data_ingestion/water_potability.csv
  report_file_path: artifacts/data_validation/report.yaml
data_transformation:
  root_dir: artifacts/data_transformation
  data_file: artifacts/data_ingestion/water_potability.csv
model_trainer:
  root_dir: artifacts/model_trainer
  data_file: artifacts/data_transformation/train_transformed.csv
  model_name: model.joblib
model_evaluation:
  root_dir: artifacts/model_evaluation
  model_file: artifacts/model_trainer/model.joblib
  data_file: artifacts/data_transformation/test_transformed.csv
  metrics_file_name: metrics.json
  

